lang: ja
timezone: Asia/Tokyo

title: y4su0.com
author:
  name: おぎうちやすお
description: > # this means to ignore newlines until "show_excerpts:"

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d %H:%M"
  skin: auto
  
  # Generate social links in footer.
  #
  social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
      - { platform: github,         user_url: "https://github.com/y4su0/" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/y4su0" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/y4su0" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
  #   - { platform: mastodon,       user_url: "https://mastodon-japan.net/@y4su0" }
  #   - { platform: misskey,        user_url: "https://misskey.io/@y4su0" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md


remote_theme: Jekyll/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-sitemap

paginate: 3
paginate_path: "/page:num/"
permalink: /:year/:month/:title.html
